obj-$(CONFIG_AX88796C) += ax88796c.o

ax88796c-objs := ax88796c_main.o ax88796c_plat_dma.o ax88796c_ioctl.o

#
#MODULE_NAME = ax88796c
#
#SRC		:= ax88796c_main.c ax88796c_plat_dma.c ax88796c_ioctl.c
#
# Path to target Linux Kernel
#KDIR		:= /root/work/2440/2.6.35/linux-2.6.35.1
# Path to cross compiler (used to build IEEE test tool).
#CC		:= /root/work/2440/2.6.35/buildroot-2010.08-rc1/output/staging/usr/bin/arm-linux-gcc
#
#$(MODULE_NAME)-objs = $(SRC:.c=.o)
#
#obj-m		:= $(MODULE_NAME).o
#PWD		:= $(shell pwd)
#
#all:
#	$(MAKE) -C $(KDIR) M=$(PWD) modules
#	$(CC) ioctl.c -o ioctl
#
#clean:
#	$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) clean
#	rm -f ioctl
#
#.PHONY: modules clean

