# SPDX-License-Identifier: GPL-2.0

snd-soc-trustphone-wm8998-objs := trustphone-wm8998.o
snd-soc-mcom03-sgtl5000-objs := mcom03-sgtl5000.o

obj-$(CONFIG_SND_SOC_ELVEES_TRUSTPHONE_WM8998) += snd-soc-trustphone-wm8998.o
obj-$(CONFIG_SND_SOC_ELVEES_SGTL5000) += snd-soc-mcom03-sgtl5000.o
